### PR TITLE
Add SwiftFormat

### PR DESCRIPTION
**Pull request by bwetherfield**
Using [SwiftFormat](https://github.com/nicklockwood/SwiftFormat#how-do-i-install-it)

### CODE REVIEW

**Comment by bwetherfield** [comment]
@jsbean, [`--self init-only`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#redundantself) is an option if you prefer to see `self` in initializers!

**Comment by jsbean** [comment]
Let's add `--self init-only`!

**Comment by bwetherfield** [comment]
Ah, so I don't think it is _that_ smart that we can revert _any_ of these changes... might need to start from square one once we agree on some formatting rules

**Comment by jsbean** [comment]
That's ok! It's lookin' good to me.

**Comment by bwetherfield** [comment]
Re-ran things so as to cause less damage!

**Pull request merged**
