### PR TITLE
Followup: fix decoding of midi-instrument and midi-device under score…

### PR DESCRIPTION
**Pull request by DJBen**
…-part

Following up - I think my work was unnecessary - all attributes are quoted, but to my surprise `XMLCoder` has already taken care of decoding numeral attributes that are in a quote.

Also I was wrong that the midi-device is a simple type. It should be a [complex type](https://www.w3schools.com/xml/schema_complex.asp)

### CODE REVIEW

**Comment by jsbean** [comment]
Nice! Perhaps we should inquire with MusicXML about this re: `CDATA` vs `PCDATA`? It seems like an oversight to me.

**Comment by jsbean** [comment]
+0 / -18 ain't so bad.

**Comment by DJBen** [comment]
> Nice! Perhaps we should inquire with MusicXML about this re: `CDATA` vs `PCDATA`? It seems like an oversight to me.

Feel free to ask!

**Comment by DJBen** [comment]
Also this is a good lesson that we should probably want to rely on the xsd definition (where the documentation is generated from) rather than dtd.

Although my gut feeling tells me [dtd](https://en.wikipedia.org/wiki/Document_type_definition) lacks ability to strictly define numerals.

**Pull request merged**
