### PR TITLE
Add test for Supports in Identification

### PR DESCRIPTION
**Pull request by DJBen**

### CODE REVIEW

**Comment by jsbean** [comment]
I actually cover this [here](https://github.com/dn-m/MusicXML/pull/176/files#diff-be327bd8e54a3aaeea8b6fd1f7020bd7R14-R51).

**Comment by DJBen** [comment]
> I actually cover this [here](https://github.com/dn-m/MusicXML/pull/176/files#diff-be327bd8e54a3aaeea8b6fd1f7020bd7R14-R51).

This test covers Supports decoding within Identification. Didn't see this being covered?

**Comment by jsbean** [comment]
Ack, the link didn't really go to the right place: https://github.com/dn-m/MusicXML/blob/1225f7b6b780e4bf9d63a35e47ee87efa88e2a21/Tests/MusicXMLTests/ReveTests.swift#L14-L51.

**Comment by jsbean** [comment]
That is, I think the tests are _identical_ :).

**Comment by DJBen** [comment]
> That is, I think the tests are _identical_ :).

gotcha

**Pull request closed without merging**
